### ISSUE TITLE
Add option to log caller threads

### ISSUE THREAD

**Issue by 3nol** [xdev-software/thread-origin-agent#12]
Hi xdev-software team,

this small `thread-origin-agent` tool is very useful!
However, I miss one additional functionality which is logging the name and ID of the caller thread, for example:

```
[TOA] Detected java.lang.Thread.start() id: 86 name: Timer-0
[TOA] Called from java.lang.Thread id: 1 name: main                                       <<< this line is new
[TOA]   java.base/java.util.Timer.<init>(timer.java:188)
[TOA]   ...
```

I opened the PR [#11](https://github.com/xdev-software/thread-origin-agent/pull/11) with this feature addition.
Feel free to reject it if you don't like it, but I'd be happy to see it integrated.

**Comment by AB-xdev** [comment]
Fixed by #11
